name: Java CI with Maven

# ${{ env.DOCKER_HELLO_IMAGE }}

on:
  push:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Bump version
      id: bump
      uses: mickem/gh-action-bump-maven-version@v1.0.0

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

  docker:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DH_USER }}
        password: ${{ secrets.DH_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.DH_USER }}/${{ vars.HELLO_IMAGE }}

  cd: 
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.SSH_HOST}}
        USER_NAME: ${{secrets.USER_NAME}}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          pwd
          docker ps
          docker run --name hello hilellelshalem/maven_hello
        '